/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ReceptionIndexRouteImport } from './routes/reception.index'
import { Route as PharmacyIndexRouteImport } from './routes/pharmacy.index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as NurseIndexRouteImport } from './routes/nurse.index'
import { Route as LabIndexRouteImport } from './routes/lab.index'
import { Route as InsuranceIndexRouteImport } from './routes/insurance.index'
import { Route as HospitalAdminIndexRouteImport } from './routes/hospital-admin.index'
import { Route as EmergencyIndexRouteImport } from './routes/emergency.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AiSuiteIndexRouteImport } from './routes/ai-suite.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionIndexRoute = ReceptionIndexRouteImport.update({
  id: '/reception/',
  path: '/reception/',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyIndexRoute = PharmacyIndexRouteImport.update({
  id: '/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/patient/',
  path: '/patient/',
  getParentRoute: () => rootRouteImport,
} as any)
const NurseIndexRoute = NurseIndexRouteImport.update({
  id: '/nurse/',
  path: '/nurse/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIndexRoute = LabIndexRouteImport.update({
  id: '/lab/',
  path: '/lab/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceIndexRoute = InsuranceIndexRouteImport.update({
  id: '/insurance/',
  path: '/insurance/',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalAdminIndexRoute = HospitalAdminIndexRouteImport.update({
  id: '/hospital-admin/',
  path: '/hospital-admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyIndexRoute = EmergencyIndexRouteImport.update({
  id: '/emergency/',
  path: '/emergency/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSuiteIndexRoute = AiSuiteIndexRouteImport.update({
  id: '/ai-suite/',
  path: '/ai-suite/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-suite/': typeof AiSuiteIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/billing/': typeof BillingIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/emergency/': typeof EmergencyIndexRoute
  '/hospital-admin/': typeof HospitalAdminIndexRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/lab/': typeof LabIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/reception/': typeof ReceptionIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-suite': typeof AiSuiteIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/billing': typeof BillingIndexRoute
  '/doctor': typeof DoctorIndexRoute
  '/emergency': typeof EmergencyIndexRoute
  '/hospital-admin': typeof HospitalAdminIndexRoute
  '/insurance': typeof InsuranceIndexRoute
  '/lab': typeof LabIndexRoute
  '/nurse': typeof NurseIndexRoute
  '/patient': typeof PatientIndexRoute
  '/pharmacy': typeof PharmacyIndexRoute
  '/reception': typeof ReceptionIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai-suite/': typeof AiSuiteIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/billing/': typeof BillingIndexRoute
  '/doctor/': typeof DoctorIndexRoute
  '/emergency/': typeof EmergencyIndexRoute
  '/hospital-admin/': typeof HospitalAdminIndexRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/lab/': typeof LabIndexRoute
  '/nurse/': typeof NurseIndexRoute
  '/patient/': typeof PatientIndexRoute
  '/pharmacy/': typeof PharmacyIndexRoute
  '/reception/': typeof ReceptionIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai-suite/'
    | '/analytics/'
    | '/billing/'
    | '/doctor/'
    | '/emergency/'
    | '/hospital-admin/'
    | '/insurance/'
    | '/lab/'
    | '/nurse/'
    | '/patient/'
    | '/pharmacy/'
    | '/reception/'
    | '/settings/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai-suite'
    | '/analytics'
    | '/billing'
    | '/doctor'
    | '/emergency'
    | '/hospital-admin'
    | '/insurance'
    | '/lab'
    | '/nurse'
    | '/patient'
    | '/pharmacy'
    | '/reception'
    | '/settings'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/ai-suite/'
    | '/analytics/'
    | '/billing/'
    | '/doctor/'
    | '/emergency/'
    | '/hospital-admin/'
    | '/insurance/'
    | '/lab/'
    | '/nurse/'
    | '/patient/'
    | '/pharmacy/'
    | '/reception/'
    | '/settings/'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AiSuiteIndexRoute: typeof AiSuiteIndexRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
  BillingIndexRoute: typeof BillingIndexRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
  EmergencyIndexRoute: typeof EmergencyIndexRoute
  HospitalAdminIndexRoute: typeof HospitalAdminIndexRoute
  InsuranceIndexRoute: typeof InsuranceIndexRoute
  LabIndexRoute: typeof LabIndexRoute
  NurseIndexRoute: typeof NurseIndexRoute
  PatientIndexRoute: typeof PatientIndexRoute
  PharmacyIndexRoute: typeof PharmacyIndexRoute
  ReceptionIndexRoute: typeof ReceptionIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception/': {
      id: '/reception/'
      path: '/reception'
      fullPath: '/reception/'
      preLoaderRoute: typeof ReceptionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/': {
      id: '/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy/'
      preLoaderRoute: typeof PharmacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/patient'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nurse/': {
      id: '/nurse/'
      path: '/nurse'
      fullPath: '/nurse/'
      preLoaderRoute: typeof NurseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/': {
      id: '/lab/'
      path: '/lab'
      fullPath: '/lab/'
      preLoaderRoute: typeof LabIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/': {
      id: '/insurance/'
      path: '/insurance'
      fullPath: '/insurance/'
      preLoaderRoute: typeof InsuranceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-admin/': {
      id: '/hospital-admin/'
      path: '/hospital-admin'
      fullPath: '/hospital-admin/'
      preLoaderRoute: typeof HospitalAdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency/': {
      id: '/emergency/'
      path: '/emergency'
      fullPath: '/emergency/'
      preLoaderRoute: typeof EmergencyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/doctor'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-suite/': {
      id: '/ai-suite/'
      path: '/ai-suite'
      fullPath: '/ai-suite/'
      preLoaderRoute: typeof AiSuiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AiSuiteIndexRoute: AiSuiteIndexRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
  BillingIndexRoute: BillingIndexRoute,
  DoctorIndexRoute: DoctorIndexRoute,
  EmergencyIndexRoute: EmergencyIndexRoute,
  HospitalAdminIndexRoute: HospitalAdminIndexRoute,
  InsuranceIndexRoute: InsuranceIndexRoute,
  LabIndexRoute: LabIndexRoute,
  NurseIndexRoute: NurseIndexRoute,
  PatientIndexRoute: PatientIndexRoute,
  PharmacyIndexRoute: PharmacyIndexRoute,
  ReceptionIndexRoute: ReceptionIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
